Use the right way to get the required feature set from glibc.
__USE_XOPEN doesn't work to get ptsname() etc. from libc.  This is
Linux-specific software so convert to _GNU_SOURCE.

make[2]: Entering directory '/home/ralf/src/ax25/ax25-tools/kiss'
gcc -DHAVE_CONFIG_H -I. -I..  -DAX25_SYSCONFDIR=\""/usr/local/etc/ax25/"\" -DAX25_LOCALSTATEDIR=\""/usr/local/var/ax25/"\"   -O
2 -Wall -pedantic -MT kissattach.o -MD -MP -MF .deps/kissattach.Tpo -c -o kissattach.o kissattach.c
kissattach.c: In function ‘main’:
kissattach.c:312:18: warning: implicit declaration of function ‘ptsname’ [-Wimplicit-function-declaration]
   if ((namepts = ptsname(fd)) == NULL) {
                  ^~~~~~~
kissattach.c:312:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   if ((namepts = ptsname(fd)) == NULL) {
                ^
kissattach.c:317:7: warning: implicit declaration of function ‘unlockpt’ [-Wimplicit-function-declaration]
   if (unlockpt(fd) == -1) {
       ^~~~~~~~
[...]
gcc -DHAVE_CONFIG_H -I. -I..  -DAX25_SYSCONFDIR=\""/usr/local/etc/ax25/"\" -DAX25_LOCALSTATEDIR=\""/usr/local/var/ax25/"\"   -O2 -Wall -pedantic -MT kissnetd.o -MD -MP -MF .deps/kissnetd.Tpo -c -o kissnetd.o kissnetd.c
kissnetd.c: In function ‘ReopenPort’:
kissnetd.c:134:16: warning: implicit declaration of function ‘ptsname’ [-Wimplicit-function-declaration]
    if ((npts = ptsname(PortList[PortNumber]->Fd)) == NULL) {
                ^~~~~~~
kissnetd.c:134:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    if ((npts = ptsname(PortList[PortNumber]->Fd)) == NULL) {
              ^
kissnetd.c:143:8: warning: implicit declaration of function ‘unlockpt’ [-Wimplicit-function-declaration]
    if (unlockpt(PortList[PortNumber]->Fd) == -1) {
        ^~~~~~~~
[...]
gcc -DHAVE_CONFIG_H -I. -I..  -DAX25_SYSCONFDIR=\""/usr/local/etc/ax25/"\" -DAX25_LOCALSTATEDIR=\""/usr/local/var/ax25/"\"   -O2 -Wall -pedantic -MT mkiss.o -MD -MP -MF .deps/mkiss.Tpo -c -o mkiss.o mkiss.c
mkiss.c: In function ‘poll’:
mkiss.c:68:15: warning: overflow in implicit constant conversion [-Woverflow]
 #define FEND  0300 /* Frame End   (0xC0) */
               ^
mkiss.c:149:14: note: in expansion of macro ‘FEND’
  buffer[0] = FEND;
              ^~~~
mkiss.c:68:15: warning: overflow in implicit constant conversion [-Woverflow]
 #define FEND  0300 /* Frame End   (0xC0) */
               ^
mkiss.c:151:14: note: in expansion of macro ‘FEND’
  buffer[2] = FEND;
              ^~~~
mkiss.c: In function ‘main’:
mkiss.c:568:16: warning: implicit declaration of function ‘ptsname’ [-Wimplicit-function-declaration]
    if ((npts = ptsname(pty[i]->fd)) == NULL) {
                ^~~~~~~
mkiss.c:568:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    if ((npts = ptsname(pty[i]->fd)) == NULL) {
              ^
mkiss.c:578:8: warning: implicit declaration of function ‘unlockpt’ [-Wimplicit-function-declaration]
    if (unlockpt(pty[i]->fd) == -1) {
        ^~~~~~~~
mkiss.c:672:33: warning: ISO C does not support the ‘%m’ gnu_printf format [-Wformat=]
      syslog(LOG_ERR, "tty->fd: %m");
                                 ^
mkiss.c:698:38: warning: ISO C does not support the ‘%m’ gnu_printf format [-Wformat=]
       syslog(LOG_ERR, "pty[%d]->fd: %m\n", i);
[...]                                      ^
gcc -DHAVE_CONFIG_H -I. -I..  -DAX25_SYSCONFDIR=\""/usr/local/etc/ax25/"\" -DAX25_LOCALSTATEDIR=\""/usr/local/var/ax25/"\"   -O2 -Wall -pedantic -MT net2kiss.o -MD -MP -MF .deps/net2kiss.Tpo -c -o net2kiss.o net2kiss.c
net2kiss.c: In function ‘main’:
net2kiss.c:630:18: warning: implicit declaration of function ‘ptsname’ [-Wimplicit-function-declaration]
   if ((namepts = ptsname(fdpty)) == NULL) {
                  ^~~~~~~
net2kiss.c:630:16: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   if ((namepts = ptsname(fdpty)) == NULL) {
                ^
net2kiss.c:635:7: warning: implicit declaration of function ‘unlockpt’ [-Wimplicit-function-declaration]
   if (unlockpt(fdpty) == -1) {
       ^~~~~~~~
[...]
gcc -DHAVE_CONFIG_H -I. -I..  -DAX25_SYSCONFDIR=\""/usr/local/etc/ax25/"\" -DAX25_LOCALSTATEDIR=\""/usr/local/var/ax25/"\"   -O2 -Wall -pedantic -MT m6pack.o -MD -MP -MF .deps/m6pack.Tpo -c -o m6pack.o m6pack.c
m6pack.c: In function ‘main’:
m6pack.c:537:16: warning: implicit declaration of function ‘ptsname’ [-Wimplicit-function-declaration]
    if ((npts = ptsname(pty[i]->fd)) == NULL) {
                ^~~~~~~
m6pack.c:537:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    if ((npts = ptsname(pty[i]->fd)) == NULL) {
              ^
m6pack.c:545:8: warning: implicit declaration of function ‘unlockpt’ [-Wimplicit-function-declaration]
    if (unlockpt(pty[i]->fd) == -1) {
        ^~~~~~~~
m6pack.c:626:33: warning: ISO C does not support the ‘%m’ gnu_printf format [-Wformat=]
      syslog(LOG_ERR, "tty->fd: %m");
                                 ^
m6pack.c:658:29: warning: ISO C does not support the ‘%m’ gnu_printf format [-Wformat=]
              "pty[%d]->fd: %m\n",i);
                             ^
[...]

Signed-off-by: Ralf Baechle <ralf@linux-mips.org>